module.exports = {
    GET_DOGS: "GET_DOGS",
    GET_ID: "GET_ID",
    GET_TEMPERAMENTS: "GET_TEMPERAMENTS",
    GET_DOGS_BY_TEMPERAMENT: "GET_DOGS_BY_TEMPERAMENT",
    GET_DOGS_BY_NAME: "GET_DOGS_BY_NAME",
    FILTER_CREATED: "FILTER_CREATED",
    SORT_BY_NAME: "SORT_BY_NAME",
    SORT_BY_WEIGHT: "SORT_BY_WEIGHT",
    POST_NEW_DOG: "POST_NEW_DOG"
} 